### ISSUE TITLE
Images for wiki

### ISSUE THREAD

**Issue by paulfitz** [paulfitz/cosmicos#20]
This is a place to stick images for use on wiki or READMEs without bulking up repo history with binary files.

**Comment by paulfitz** [comment]
![cos_message_picture](https://cloud.githubusercontent.com/assets/118367/17651667/c896d2a4-6239-11e6-9906-606475b5e4ef.png)
![cos_zipfs_law](https://cloud.githubusercontent.com/assets/118367/17651666/c896dbc8-6239-11e6-9f29-78f1cf4ecf3f.png)

**Comment by paulfitz** [comment]
![cos_entropy_ngram-length](https://cloud.githubusercontent.com/assets/118367/17651672/f7f4788a-6239-11e6-8bc2-ece529eec5c9.png)

**Comment by joha2** [comment]
![cos_entropy_ngram-length_new](https://cloud.githubusercontent.com/assets/12564815/17652069/f36c6342-6273-11e6-8aa0-5676a7736c60.png)

new version of entropy plot

**Comment by paulfitz** [comment]
closing "issue", fine to keep posting images here though :-)

**Comment by joha2** [comment]
;-)

**Comment by joha2** [comment]
![cos_message_picture_new](https://cloud.githubusercontent.com/assets/12564815/17677391/da189e5a-6332-11e6-87c7-e21fa777df42.png)

**Comment by paulfitz** [comment]
![d](https://user-images.githubusercontent.com/118367/64082227-b9e0d580-ccd9-11e9-89db-dee9920a771f.gif)
