### ISSUE TITLE
Upgrade TravisCI

### ISSUE THREAD

**Issue by aw1231** [paulfitz/cosmicos#35]
The old TravisCI actions are outdated and preventing pull requests from being analyzed (notably #33). Adding github checks per [this post](https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154) should fix it.

**Comment by paulfitz** [comment]
Switched to github actions.
