### ISSUE TITLE
Haxe automated build broken by neko dependency

### ISSUE THREAD

**Issue by aw1231** [paulfitz/cosmicos#8]
Hi,
Just wanted to let you know that neko isn't available on Travis so the automated build fails.  I opened an issue with Travis to fix this.

**Comment by paulfitz** [comment]
Thanks @aw1231 - one idea could be to use a haxe ppa, see e.g. https://github.com/paulfitz/daff/blob/master/.travis.yml#L13

**Comment by aw1231** [comment]
If I understand PPAs correctly, they are just prebulit binaries.  Is that correct?

**Comment by aw1231** [comment]
Anywho, this is fixed by #13.  PPA usage might still be useful though.
